### ISSUE TITLE
No longer working on macOS

### ISSUE THREAD

**Issue by absolutejam** [ul/kak-lsp#226]
Meant to raise an issue about this a while ago, but I've been making do (although barely 🙈). I have tried building from source, from brew, building the previous version and both the latest version of Kakoune and the previous one.

## Current setup

```bash
kak -version
Kakoune v2019.01.20
```

```bash
kak-lsp --version
kak-lsp 6.0.1
```

kak-lsp.toml
```toml
verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.elixir]
filetypes = ["elixir"]
roots = [".git", "mix.exs"]
command = "elixir-ls"

[language.php]
filetypes = ["php"]
roots = ["composer.json",".git"]
command = "php-ls"

[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pyls"

[language.ruby]
filetypes = ["ruby"]
roots = ["Gemfile"]
command = "solargraph"
args = ["stdio"]

# -- UNUSED ---

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

[language.javascript]
filetypes = ["javascript"]
roots = ["package.json"]
command = "flow"
args = ["lsp"]

[language.json]
filetypes = ["json"]
roots = ["package.json"]
command = "json-languageserver"
args = ["--stdio"]

[language.css]
filetypes = ["css"]
roots = ["package.json"]
command = "css-languageserver"
args = ["--stdio"]

[language.html]
filetypes = ["html"]
roots = ["package.json"]
command = "html-languageserver"
args = ["--stdio"]

[language.ocaml]
filetypes = ["ocaml"]
roots = ["Makefile", "opam", "*.opam"]
command = "ocaml-language-server"
args = ["--stdio"]

[language.reason]
filetypes = ["reason"]
roots = ["package.json", "Makefile", ".git", ".hg"]
command = "ocaml-language-server"
args = ["--stdio"]

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".cquery"]
command = "cquery"
args = ["--init={\"cacheDirectory\":\"/tmp/cquery\"}"]

[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "hie"
args = ["--lsp"]

[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "go-langserver"
args = ["-mode", "stdio", "-gocodecompletion"]

[language.bash]
filetypes = ["sh"]
roots = [".git", ".hg"]
command = "bash-language-server"
args = ["start"]

[language.dart]
filetypes = ["dart"]
roots = ["pubspec.yaml", ".git"]
command = "dart_language_server"

[language.d]
filetypes = ["d", "di"]
roots = [".git", "dub.sdl", "dub.json"]
command = "dls"
```

---

## Testing

Using tmux, In one pane:
```sh
kak -vvv -s -foo
```

In another:
```sh
kak -s foo
```

**test.py**
```python
#!/usr/bin/env python3
class Waffle():
    def __init__(self):
        print("Tasty")

w = Waffle()
#      ^--- cursor
```

Show capabilities - This works.
```bash
Jul 21 21:18:56.036 DEBG From editor:
session  = "foo"
client   = "client0"
buffile  = "/Users/james/Desktop/test.py"
filetype = "python"
version  = 1
method   = "textDocument/didChange"
[params]
draft    = """
class Waffle():
    def __init__(self):
        print(\"Waffle\")

c = Waffle()
"""
, module: kak_lsp::editor_transport:151
Jul 21 21:18:56.037 DEBG Routing editor request to Route { session: "foo", language: "python", root: "/Users/james/Desktop" }, module: kak_lsp::session:117
Jul 21 21:18:56.038 INFO Starting Language server `pyls `, module: kak_lsp::language_server_transport:19
Jul 21 21:18:56.040 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"colorProvider":null,"completion":{"compl
etionItem":{"documentationFormat":["plaintext"]}}},"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"]}}},"
processId":23612,"rootUri":"file:///Users/james/Desktop","trace":"off"},"id":0}, module: kak_lsp::language_server_transport:149
Jul 21 21:18:56.075 DEBG From editor:
session  = "foo"
client   = "client0"
buffile  = "/Users/james/Desktop/test.py"
filetype = "python"
version  = 1
method   = "capabilities"
[params]
, module: kak_lsp::editor_transport:151
Jul 21 21:18:56.077 DEBG Routing editor request to Route { session: "foo", language: "python", root: "/Users/james/Desktop" }, module: kak_lsp::session:117
Jul 21 21:18:56.077 DEBG Language server is not initialized, parking request, module: kak_lsp::controller:67
Jul 21 21:18:56.081 DEBG To editor `foo`: eval -client client0 'lsp-show-error ''Language server is not initialized, parking request''', module: kak_lsp::edit
or_transport:81
Jul 21 21:18:56.817 DEBG From server: {"jsonrpc": "2.0", "id": 0, "result": {"capabilities": {"codeActionProvider": true, "codeLensProvider": {"resolveProvide
r": false}, "completionProvider": {"resolveProvider": false, "triggerCharacters": ["."]}, "documentFormattingProvider": true, "documentHighlightProvider": tru
e, "documentRangeFormattingProvider": true, "documentSymbolProvider": true, "definitionProvider": true, "executeCommandProvider": {"commands": []}, "hoverProv
ider": true, "referencesProvider": true, "renameProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "textDocumentSync": 2, "experimen
tal": {}}}}, module: kak_lsp::language_server_transport:129
Jul 21 21:18:56.817 DEBG To server: {"jsonrpc":"2.0","method":"initialized","params":{}}, module: kak_lsp::language_server_transport:149
Jul 21 21:18:56.817 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"python","text":"class Waffle():\n
    def __init__(self):\n        print(\"Waffle\")\n\nc = Waffle()\n","uri":"file:///Users/james/Desktop/test.py","version":1}}}, module: kak_lsp::language_se
rver_transport:149
Jul 21 21:18:56.819 DEBG To editor `foo`: eval -client client0 'info ''kak-lsp commands supported by python language server:

lsp-hover
lsp-completion (hooked on InsertIdle)
lsp-definition (mapped to `gd` by default)
lsp-references
lsp-formatting
lsp-rename
lsp-diagnostics''', module: kak_lsp::editor_transport:81
Jul 21 21:18:57.330 DEBG From server: {"jsonrpc": "2.0", "method": "textDocument/publishDiagnostics", "params": {"uri": "file:///Users/james/Desktop/test.py",
 "diagnostics": [{"source": "pycodestyle", "range": {"start": {"line": 4, "character": 0}, "end": {"line": 4, "character": 13}}, "message": "E305 expected 2 b
lank lines after class or function definition, found 1", "code": "E305", "severity": 2}]}}, module: kak_lsp::language_server_transport:129
Jul 21 21:18:57.331 DEBG To editor `foo`:
        eval -buffer '/Users/james/Desktop/test.py' 'set buffer lsp_diagnostic_error_count 0
         set buffer lsp_diagnostic_warning_count 1
         set buffer lsp_errors 1 5.1,5.13|DiagnosticWarning
         eval "set buffer lsp_error_lines 1 5|%opt[lsp_diagnostic_line_warning_sign] ''1| '' "', module: kak_lsp::editor_transport:81
```

`lsp-hover`
```bash
Jul 21 21:20:07.765 DEBG From editor:
session   = "foo"
client    = "client0"
buffile   = "/Users/james/Desktop/test.py"
filetype  = "python"
version   = 1
method    = "textDocument/hover"
[params.position]
line      = 5
column    = 5
, module: kak_lsp::editor_transport:151
Jul 21 21:20:07.765 DEBG Routing editor request to Route { session: "foo", language: "python", root: "/Users/james/Desktop" }, module: kak_lsp::session:117
Jul 21 21:20:07.765 ERRO Params should follow PositionParams structure, module: kak_lsp::language_features::hover:15
```

Go to definition
```
Jul 21 21:21:17.214 DEBG From editor:
session   = "foo"
client    = "client0"
buffile   = "/Users/james/Desktop/test.py"
filetype  = "python"
version   = 1
method    = "textDocument/definition"
[params.position]
line      = 5
column    = 5
, module: kak_lsp::editor_transport:151
Jul 21 21:21:17.214 DEBG Routing editor request to Route { session: "foo", language: "python", root: "/Users/james/Desktop" }, module: kak_lsp::session:117
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing f
ield `character`", key: ["position"] } }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Jul 21 21:21:17.215 ERRO Params should follow PositionParams structure, module: kak_lsp::language_features::definition:13
Jul 21 21:21:17.215 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:160
Jul 21 21:21:17.216 ERRO Failed to join controller thread, module: kak_lsp::session:75
Jul 21 21:21:17.299 DEBG Language server closed pipe, stopping reading, module: kak_lsp::language_server_transport:107
Jul 21 21:21:17.299 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:57
Jul 21 21:21:17.299 DEBG Sending exit notification back to controller, module: kak_lsp::language_server_transport:67
```

Any ideas where to start? Anything I can do to provide more info/context?
