### ISSUE TITLE
Language server repeatedly disconnecting and reconnecting (GDScript)

### ISSUE THREAD

**Issue by BanchouBoo** [ul/kak-lsp#308]
Godot uses TCP for it's language server (godotengine/godot#35864) and I'm trying to use `netcat` to interface with it (this works in [neovim](https://github.com/neovim/nvim-lsp#gdscript)), but the connection repeatedly starts and stops and `kak-lsp` doesn't have any effect inside the editor.

![image](https://user-images.githubusercontent.com/32691832/78601768-4da3f280-7823-11ea-9d4e-5c623800d96e.png)

The configuration in `kak-lsp.toml` is as follows:

```toml
[language.gdscript]
filetypes = ["gd", "gdscript"]
roots = [".import"]
command = "nc"
args = ["localhost", "6008"]
```

The log from `kak-lsp` can be viewed at https://hatebin.com/jpptemlpdu
