### ISSUE TITLE
Is there a way to find the mappings for the Semantic Highligthing?

### ISSUE THREAD

**Issue by arrufat** [ul/kak-lsp#310]
I've just updated to clangd 10 and I've noticed there are many new semantic highlighting scopes:
```
[["variable.other.cpp"],
["variable.other.local.cpp"],
["variable.parameter.cpp"],
["entity.name.function.cpp"],
["entity.name.function.method.cpp"],
["entity.name.function.method.static.cpp"]
["variable.other.field.cpp"],
["variable.other.field.static.cpp"],
["entity.name.type.class.cpp"],
["entity.name.type.enum.cpp"],
["variable.other.enummember.cpp"],
["entity.name.type.typedef.cpp"],
["entity.name.type.dependent.cpp"],
["entity.name.other.dependent.cpp"],
["entity.name.namespace.cpp"],
["entity.name.type.template.cpp"],
["storage.type.primitive.cpp"],
["entity.name.function.preprocessor.cpp"],
["meta.disabled"]]
```
Some of them are already mapped in the default `kak-lsp.toml` file. But how about the others? Is there a place where I can find the mappings? Thanks in advance :)

**Comment by topisani** [comment]
The ones that aren't in kak-lsp.toml aren't mapped to anything. You can set them if you want to. And remember that you only need to map a prefix of the scope

**Comment by arrufat** [comment]
@topisani thanks for the quick response.

Currently I have the following mappings.
``` toml
[semantic_scopes]
variable="variable"
entity_name_function="function"
entity_name_function_method="memberFunction"
variable_other_field="memberVariable"
entity_name_type="type"
variable_other_enummember="variable"
entity_name_namespace="module"
entity_name_type_template_cpp="type"
entity_name_function_preprocessor="cppMacro"
meta_disabled="disabledRegion"
```
I guess I wasn't clear enough with my question. I would like to know how to find out what are the possible names on the right hand side: "variable", "function", "type", "module", etc.
