### ISSUE TITLE
No diagnostics, completion, or hover for any language server

### ISSUE THREAD

**Issue by The-BigDaddy** [ul/kak-lsp#363]
So I have this on the [Kakoune Community site](https://discuss.kakoune.com/t/i-have-no-idea-if-kak-lsp-is-running/1093), but to have it here for others to look.

Here's the output of `uname -a` (for the sake of it):

    Linux my-void 5.4.46_1 #1 SMP PREEMPT Wed Jun 10 19:33:58 UTC 2020 x86_64 GNU/Linux

`kak -version`: Kakoune v2020.01.16-273-g74e3e5ef

`kak-lsp -V`: kak-lsp 8.0.0-snapshot (I'm on the most recent master)

Here's the bit from my kakoune config for kak-lsp:

```
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path . --locked
    cargo clean
} config %{
	
    set-option global lsp_cmd "kak-lsp --kakoune -vvv -c $HOME/.config/kak-lsp/kak-lsp.toml -s %val{session} --log $HOME/.config/kak-lsp/kak-lsp.log"

    define-command lsp-restart %{ lsp-stop; lsp-start }

    set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\s,=;*(){}\[\]]\z<ret>'"
    set-option global lsp_diagnostic_line_error_sign "!"
    set-option global lsp_diagnostic_line_warning_sign "?"
    hook global WinSetOption filetype=(c|cpp|objc|d|rust|haskell|nim|elixir|latex|javascript) %{

        lsp-start
    	lsp-enable-window
    	echo -debug "Enabling LSP for filtetype %opt{filetype}"
    	
    	lsp-auto-hover-enable
    	lsp-auto-hover-insert-mode-disable
    	set-option global lsp_auto_highlight_references true
    	set-option global lsp_hover_anchor true
    	
    	# Semantic highlighting
    	hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
    	hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
    	hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
    	hook -once -always window WinSetOption filetype=.* %{
    		 remove-hooks window semantic-tokens
    	}
    	
    	# Other things
    	# hook window BufWritePre .* lsp-formatting-sync
    	hook window BufWritePost .* lsp-diagnostics
    	hook -always global KakEnd .* lsp-exit
        hook global WinSetOption filetype=rust %{
            set-option window lsp_server_configuration rust.clippy_preference="on"
        }
    }
}
```

And my `kak-lsp.toml`:

```toml
lsp_hover_anchor=true
lsp_hover_max_lines=6
snippet_support = true
verbosity = 3

[semantic_scopes]
# Map textmate scopes to kakoune faces for semantic highlighting
# the underscores are translated to dots, and indicate nesting.
# That is, if variable_other_field is omitted, it will try the face for
# variable_other and then variable
#
# To see a list of available scopes in the debug buffer, run lsp-semantic-available-scopes
variable = "variable"
entity_name_function = "function"
entity_name_type = "type"
variable_other_enummember = "variable"
entity_name_namespace = "module"

# Semantic tokens support
# See https://github.com/microsoft/vscode-languageserver-node/blob/8c8981eb4fb6adec27bf1bb5390a0f8f7df2899e/client/src/semanticTokens.proposed.ts#L288
# for token/modifier types.

[semantic_tokens]
type = "type"
variable = "variable"
namespace = "module"
function = "function"
string = "string"
keyword = "keyword"
operator = "operator"
comment = "comment"

[semantic_modifiers]
documentation = "documentation"
readonly = "default+d"

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.c_cpp]
filetypes = ["c", "cpp", "objc", "objcpp", "cuda"]
roots = [".ccls", "compile_commands.json"]
command = "ccls"
args= ["--init={\"completion\":{\"detailedLabel\":false},\"highlight\":{\"lsRanges\":true}"]

[language.d]
filetypes = ["d", "di"]
roots = [".git", "dub.sdl", "dub.json"]
command = "dls"

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"

[language.haskell]
filetypes = ["haskell"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

[language.nim]
filetypes = ["nim"]
roots = ["*.nimble", ".git"]
command = "nimlsp"

[language.elixir]
filetypes = ["elixir", "exs", "eex"]
roots = ["mix.exs"]
command = "~/Tools/Elixir/elixir-ls/release/language_server.sh"

[language.latex]
filetypes = ["latex"]
roots = [".git"]
command = "texlab"

[language.javascript]
filetypes = ["javascript"]
roots = ["package.json", "jsconfig.json"]
command = "tsserver"

[language.typescript]
filetypes = ["typescript"]
roots = ["package.json", "tsconfig.json"]
command = "tsserver"
```

All the executables for the language servers are in my `$PATH` (I can run `:eval %sh{ echo $PATH }` and get all the correct directories in `$PATH`), and I can run them outside of Kakoune.

I get the feeling there's one silly thing that I've done that's giving me troubles, but I'm not sure as to what it is.
