### ISSUE TITLE
pyright-langserver stops working after lsp-exit

### ISSUE THREAD

**Issue by ttttcrngyblflpp** [ul/kak-lsp#672]
I'm observing that when kakoune starts, I can make use of pyright-langserver functionality, but as soon as the LSP server is restarted (I don't really know exactly when this happens, but I can intentionally make this happen using `:lsp-exit`), nothing works anymore. It looks like the difference is that after `:lsp-exit`, pyright-langserver is no longer able to find any source files. My workaround for now is doing `:lsp-disable` and `:lsp-enable`...

I have reproduced this with the following minimal kak-lsp configuration:

```toml
[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pyright-langserver"
args = ["--stdio"]
```

and the following minimal python file:

```python
class Foo(object):
    pass

class Bar(Foo):
    pass
```

Here is a set of logs I collected, search for `XXX` to see the markers I inserted after certain steps were taken: [kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10788174/kak-lsp.log).

kak-lsp version is `kak-lsp 14.2.0-snapshot`.
